export const icons = {
  'slide-1': require('../images/slide-1.png'),
  'slide-2': require('../images/slide-2.png'),
  'slide-3': require('../images/slide-3.png'),
  logo: require('../images/logo.png'),
  eye: require('../images/eye.png'),
  'eye-closed': require('../images/eye-closed.png'),
  facebook: require('../images/facebook.png'),
  google: require('../images/google.png'),
  apple: require('../images/apple.png'),
  research: require('../images/research.png'),
  finance: require('../images/finance.png'),
  home: require('../images/Home.png'),
  vacancies: require('../images/Vacancies.png'),
  more: require('../images/more.png'),
  plus: require('../images/plus-circle.png'),
  candidates: require('../images/candidates.png'),
  pencil: require('../images/pencil.png'),
  calendar: require('../images/calendar.png'),
  dot: require('../images/3-dot.png'),
  avatar: require('../images/avatar.png'),
  avatar1: require('../images/avatar-12.png'),
  pluss: require('../images/plus.png'),
};

export type IconTypes = keyof typeof icons;
